# Generated by Django 4.2.1 on 2023-05-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_description',
            new_name='dep_description',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='dep_name',
        ),
    ]
